var txt = "Hello World!";
document.write("ZSE najlepszą szkoła w kodowaniu " + txt);
document.write("<p>Big: " + txt.big() + "</p>");
document.write("<p>Small: " + txt.small() + "</p>");
document.write("<p>Bold: " + txt.bold() + "</p>");
document.write("<p>Italic: " + txt.italics() + "</p>");
document.write("<p>Fixed: " + txt.fixed() + "</p>");
document.write("<p>Strike: " + txt.strike() + "</p>");
document.write("<p>Fontcolor: " + txt.fontcolor("green") + "</p>");
document.write("<p>Fontsize: " + txt.fontsize(6) + "</p>");
document.write("<p>Subscript: " + txt.sub() + "</p>");
document.write("<p>Superscript: " + txt.sup() + "</p>");
document.write("<p>Link: " + txt.link("https://www.youtube.com/watch?v=dQw4w9WgXcQ") + "</p>");
document.write("<p>Blink: " + txt.blink() + " (works only in Opera)</p>");
document.write("ostatnia modyfikacja strony".fontcolor("red").bold().fontsize(7)+"<br>");
document.write(document.lastModified.strike().bold().fontcolor("maroon").fontsize(7));